// JavaScript Document
document.body.addEventListener('touchstart', function () { }); 
  
  //延迟加载
window.Echo=(function(win,doc,undefined){var store=[],offset,effectClass,poll,ticking=false,classList="classList" in document.documentElement?1:0;var _inView=function(el){var coords=el.getBoundingClientRect();return((coords.top>=0&&coords.left>=0&&coords.top)<=(win.innerHeight||doc.documentElement.clientHeight)+parseInt(offset))};var _throttle=function(){if(!ticking){requestAnimationFrame(_pollImages)}ticking=true};var _pollImages=function(){if(store.length>0){for(var i=store.length;i--;){var self=store[i];if(_inView(self)){self.src=self.getAttribute("data-echo");var hasBk=self.getAttribute("data-echo-background");if(hasBk){self.style.backgroundImage="url("+self.getAttribute("data-echo-background")+")"}if(effectClass){if(classList){self.classList.add(effectClass)}else{self.className+=" "+effectClass}}store.splice(i,1);self.removeAttribute("data-echo");if(hasBk){self.removeAttribute("src");self.removeAttribute("data-echo-background")}}}}ticking=false};var init=function(obj){var nodes=doc.querySelectorAll("[data-echo], [data-echo-background]");var opts=obj||{};offset=opts.offset||0;effectClass=opts.effectClass;for(var i=0;i<nodes.length;i++){store.push(nodes[i])}_throttle();if(doc.addEventListener){win.addEventListener("scroll",_throttle,false)}else{win.attachEvent("onscroll",_throttle)}};return{init:init,render:_throttle}})(window,document);

 //requestAnimationFrame兼容
;(function(){var lastTime=0;var vendors=["ms","moz","webkit","o"];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[vendors[x]+"CancelAnimationFrame"]||window[vendors[x]+"CancelRequestAnimationFrame"]}if(!window.requestAnimationFrame){window.requestAnimationFrame=function(callback,element){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall)},timeToCall);lastTime=currTime+timeToCall;return id}}if(!window.cancelAnimationFrame){window.cancelAnimationFrame=function(id){clearTimeout(id)}}}());

 //我的常用函数
Sky={myOffsetTop:function(obj,offset){var nowTop=Sky.getTop(obj)+offset;window.scrollTo(0,nowTop)},getStyle:function(obj,attr){return obj.currentStyle?obj.currentStyle[attr]:getComputedStyle(obj,false)[attr]},getClass:function(parent,className,tagName){var parent=parent||document,tagName=tagName||"*";if(parent.getElementsByClassName){return parent.getElementsByClassName(className)}else{var aEls=parent.getElementsByTagName(tagName),arr=[],re=new RegExp("(^|\\s)"+className+"($|\\s)");for(var i=0;i<aEls.length;i++){re.test(aEls[i].className)&&arr.push(aEls[i])}return arr}},bind:function(obj,type,fn){if(obj.addEventListener){obj.addEventListener(type,fn,false)}else{obj.attachEvent("on"+type,function(){fn.call(obj)})}},removeBind:function(obj,type,fn){if(obj.removeEventListener){obj.removeEventListener(type,fn,false)}else{obj.detachEvent("on"+type,function(){fn.call(obj)})}},getTop:function(obj){var iTop=0;while(obj){iTop+=obj.offsetTop;obj=obj.offsetParent}return iTop}};
		  
 //dom ready
var domReady=(function(){var funcs=[];var ready=false;function handler(e){if(ready){return}if(e.type==="onreadystatechange"&&document.readyState!=="complete"){return}for(var i=0;i<funcs.length;i++){funcs[i].call(document)}ready=true;funcs=null}if(document.addEventListener){document.addEventListener("DOMContentLoaded",handler,false);document.addEventListener("readystatechange",handler,false);window.addEventListener("load",handler,false)}else{if(document.attachEvent){document.attachEvent("onreadystatechange",handler);window.attachEvent("onload",handler)}}return function whenReady(fn){if(ready){fn.call(document)}else{funcs.push(fn)}}})();


/*touch  */
;(function(D,f){if(typeof D.createEvent!=="function"){return false}var l=typeof jQuery!=="undefined",a=function(G){var F=G.toLowerCase(),E="MS"+G;return navigator.msPointerEnabled?E:F},t=!!navigator.pointerEnabled||navigator.msPointerEnabled,n=function(){return"ontouchstart" in f||f.DocumentTouch&&D instanceof DocumentTouch||t},y=function(G){var E=n(),F=/mouse/.test(G.type);return !F&&E&&/touch/.test(G.type)&&!t||!F&&E&&!/touch/.test(G.type)&&t||F&&!E},w={touchstart:a("PointerDown")+" touchstart",touchend:a("PointerUp")+" touchend",touchmove:a("PointerMove")+" touchmove"},j=function(I,G,H){var E=G.split(" "),F=E.length;while(F--){I.addEventListener(E[F],H,false)}},g=function(E){return E.targetTouches?E.targetTouches[0]:E},k=function(){return new Date().getTime()},i=function(J,F,E,I){var H=D.createEvent("Event");H.originalEvent=E;I=I||{};I.x=s;I.y=p;I.distance=I.distance;if(l){H=$.Event(F,{originalEvent:E});jQuery(J).trigger(H,I)}if(H.initEvent){for(var G in I){H[G]=I[G]}H.initEvent(F,true,true);J.dispatchEvent(H)}if(J["on"+F]){J["on"+F](H)}},d=function(E){if(!y(E)){return}var F=g(E);v=s=F.pageX;u=p=F.pageY;r=setTimeout(function(){i(E.target,"longtap",E);C=E.target},x);c=k();m++},b=function(K){if(!y(K)){return}var J=[],H=k(),E=u-p,F=v-s;clearTimeout(B);clearTimeout(r);if(F<=-o){J.push("swiperight")}if(F>=o){J.push("swipeleft")}if(E<=-o){J.push("swipedown")}if(E>=o){J.push("swipeup")}if(J.length){for(var I=0;I<J.length;I++){var G=J[I];i(K.target,G,K,{distance:{x:Math.abs(F),y:Math.abs(E)}})}}else{if(v>=s-z&&v<=s+z&&u>=p-z&&u<=p+z){if(c+h-H>=0){i(K.target,m===2&&C===K.target?"dbltap":"tap",K);C=K.target}}B=setTimeout(function(){m=0},A)}},e=function(E){if(!y(E)){return}var F=g(E);s=F.pageX;p=F.pageY},o=f.SWIPE_THRESHOLD||100,h=f.TAP_THRESHOLD||150,A=f.DBL_TAP_THRESHOLD||200,x=f.LONG_TAP_THRESHOLD||1000,z=f.TAP_PRECISION/2||60/2,q=f.JUST_ON_TOUCH_DEVICES,m=0,s,p,v,u,c,C,B,r;j(D,w.touchstart+(q?"":" mousedown"),d);j(D,w.touchend+(q?"":" mouseup"),b);j(D,w.touchmove+(q?"":" mousemove"),e)}(document,window));

// ajax
function YAjax(){this._self=this;this.xmlhttp=this.init()}YAjax.prototype={constructor:YAjax,init:function(){var xmlhttp=null;if(window.XMLHttpRequest){xmlhttp=new XMLHttpRequest();if(xmlhttp.overrideMimeType){xmlhttp.overrideMimeType("text/xml")}}else{if(window.ActiveXObject){var activexName=["MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(var i=0;i<activexName.length;i++){try{xmlhttp=new ActiveXObject(activexName[i]);break}catch(e){}}}}return xmlhttp},extend:function(destination,source,override){if(undefined==override){override=true}if(typeof destination!="object"&&typeof destination!="function"){if(!override){return destination}else{destination={}}}var property="";for(property in source){if(override||!(property in destination)){destination[property]=source[property]}}return destination},json2String:function(jsonData){var strArr=[];for(var k in jsonData){strArr.push(k+"="+jsonData[k])}return strArr.join("&")},request:function(opt){var _self=this,isTimeout=false,timeFlag=0,options={url:"",data:"",method:"POST",receiveType:"html",timeout:7000,async:true,success:function(){alert("define your success function")},error:function(xmlhttp){}};if("data" in opt){if(typeof opt.data=="string"){}else{opt.data=this.json2String(opt.data)}}options=this.extend(options,opt);this.xmlhttp.onreadystatechange=function(){if(_self.xmlhttp.readyState==4){if(!isTimeout&&_self.xmlhttp.status==200){clearTimeout(timeFlag);var t=options.receiveType.toLowerCase();if(t=="html"){options.success(_self.xmlhttp.responseText)}else{if(t=="xml"){options.success(_self.xmlhttp.responseXML)}else{if(t=="json"){try{var obj=JSON.parse(_self.xmlhttp.responseText);options.success(obj)}catch(e){var str="("+_self.xmlhttp.responseText+")";options.success(eval(str))}}else{}}}}else{clearTimeout(timeFlag);options.error(_self.xmlhttp)}}};timeFlag=setTimeout(function(){if(_self.xmlhttp.readyState!=4){isTimeout=true;_self.xmlhttp.abort();clearTimeout(timeFlag)}},options.timeout);this.xmlhttp.open(options.method.toUpperCase(),options.url,options.async);if(options.method.toUpperCase()=="POST"){this.xmlhttp.setRequestHeader("Content-Type","application/x-www-form-urlencoded");this.xmlhttp.send(options.data)}else{this.xmlhttp.send(null)}}};


// url字符串截取
var getQueryString=function(name){var reg=new RegExp("(^|&)"+name+"=([^&]*)(&|$)","i");var r=window.location.search.substr(1).match(reg);if(r!=null){return unescape(r[2])}return""};

var myTap= !!("ontouchstart" in window )? "touchstart":"click";
var myClick= !!("ontouchend" in window )? "ontouchend":"onclick";

//优化高频函数	
var throttle=function(fn,timeout){var timer;return function(){var self=this,args=arguments;clearTimeout(timer);timer=setTimeout(function(){fn.apply(self,args)},timeout)}};

//是否微信
var userAgent=window.navigator.userAgent.toLowerCase(),isWeixin = userAgent.indexOf('micromessenger') !== -1;
